/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KesfetRouteImport } from './routes/kesfet'
import { Route as KaydedilenlerRouteImport } from './routes/kaydedilenler'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as AtolyeRouteImport } from './routes/atolye'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfilUsernameRouteImport } from './routes/profil.$username'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'

const KesfetRoute = KesfetRouteImport.update({
  id: '/kesfet',
  path: '/kesfet',
  getParentRoute: () => rootRouteImport,
} as any)
const KaydedilenlerRoute = KaydedilenlerRouteImport.update({
  id: '/kaydedilenler',
  path: '/kaydedilenler',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyeRoute = AtolyeRouteImport.update({
  id: '/atolye',
  path: '/atolye',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfilUsernameRoute = ProfilUsernameRouteImport.update({
  id: '/profil/$username',
  path: '/profil/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/admin/posts': typeof AdminPostsRoute
  '/profil/$username': typeof ProfilUsernameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/admin/posts': typeof AdminPostsRoute
  '/profil/$username': typeof ProfilUsernameRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/admin/posts': typeof AdminPostsRoute
  '/profil/$username': typeof ProfilUsernameRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/admin/posts'
    | '/profil/$username'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/admin/posts'
    | '/profil/$username'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/admin/posts'
    | '/profil/$username'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AtolyeRoute: typeof AtolyeRoute
  BildirimlerRoute: typeof BildirimlerRoute
  KaydedilenlerRoute: typeof KaydedilenlerRoute
  KesfetRoute: typeof KesfetRoute
  ProfilUsernameRoute: typeof ProfilUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kesfet': {
      id: '/kesfet'
      path: '/kesfet'
      fullPath: '/kesfet'
      preLoaderRoute: typeof KesfetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaydedilenler': {
      id: '/kaydedilenler'
      path: '/kaydedilenler'
      fullPath: '/kaydedilenler'
      preLoaderRoute: typeof KaydedilenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolye': {
      id: '/atolye'
      path: '/atolye'
      fullPath: '/atolye'
      preLoaderRoute: typeof AtolyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profil/$username': {
      id: '/profil/$username'
      path: '/profil/$username'
      fullPath: '/profil/$username'
      preLoaderRoute: typeof ProfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminPostsRoute: typeof AdminPostsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminPostsRoute: AdminPostsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AtolyeRoute: AtolyeRoute,
  BildirimlerRoute: BildirimlerRoute,
  KaydedilenlerRoute: KaydedilenlerRoute,
  KesfetRoute: KesfetRoute,
  ProfilUsernameRoute: ProfilUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
