/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KesfetRouteImport } from './routes/kesfet'
import { Route as KaydedilenlerRouteImport } from './routes/kaydedilenler'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as AtolyeRouteImport } from './routes/atolye'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilUsernameRouteImport } from './routes/profil.$username'

const KesfetRoute = KesfetRouteImport.update({
  id: '/kesfet',
  path: '/kesfet',
  getParentRoute: () => rootRouteImport,
} as any)
const KaydedilenlerRoute = KaydedilenlerRouteImport.update({
  id: '/kaydedilenler',
  path: '/kaydedilenler',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const AtolyeRoute = AtolyeRouteImport.update({
  id: '/atolye',
  path: '/atolye',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilUsernameRoute = ProfilUsernameRouteImport.update({
  id: '/profil/$username',
  path: '/profil/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/profil/$username': typeof ProfilUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/profil/$username': typeof ProfilUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atolye': typeof AtolyeRoute
  '/bildirimler': typeof BildirimlerRoute
  '/kaydedilenler': typeof KaydedilenlerRoute
  '/kesfet': typeof KesfetRoute
  '/profil/$username': typeof ProfilUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/profil/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/profil/$username'
  id:
    | '__root__'
    | '/'
    | '/atolye'
    | '/bildirimler'
    | '/kaydedilenler'
    | '/kesfet'
    | '/profil/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtolyeRoute: typeof AtolyeRoute
  BildirimlerRoute: typeof BildirimlerRoute
  KaydedilenlerRoute: typeof KaydedilenlerRoute
  KesfetRoute: typeof KesfetRoute
  ProfilUsernameRoute: typeof ProfilUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kesfet': {
      id: '/kesfet'
      path: '/kesfet'
      fullPath: '/kesfet'
      preLoaderRoute: typeof KesfetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaydedilenler': {
      id: '/kaydedilenler'
      path: '/kaydedilenler'
      fullPath: '/kaydedilenler'
      preLoaderRoute: typeof KaydedilenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atolye': {
      id: '/atolye'
      path: '/atolye'
      fullPath: '/atolye'
      preLoaderRoute: typeof AtolyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$username': {
      id: '/profil/$username'
      path: '/profil/$username'
      fullPath: '/profil/$username'
      preLoaderRoute: typeof ProfilUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtolyeRoute: AtolyeRoute,
  BildirimlerRoute: BildirimlerRoute,
  KaydedilenlerRoute: KaydedilenlerRoute,
  KesfetRoute: KesfetRoute,
  ProfilUsernameRoute: ProfilUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
